app/controllers/deny_web/forms.py
from wtforms import StringField, DateField, BooleanField, Form, IntegerField, SelectField, validators


class DenyWebForm(Form):
    web = StringField(u'web')
    document = StringField(u'document')
    status = SelectField(u'status', choices=[(0, 'DENY'), (1, 'ACCEPT'), (2, 'WAITING')])

app/controllers/deny_web/__init__.py
from flask import Blueprint
deny_web = Blueprint('deny_web', __name__)
from . import views

app/controllers/deny_web/views.py
# -*- coding:utf-8 -*-
from flask import render_template, flash, request, redirect, url_for
from app.controllers.deny_web import deny_web
from flask_login import login_required
from flask import send_file
import os, json
import csv
from app.controllers.deny_web.forms import DenyWebForm
import uuid
from core.helpers.stringhelpers import check_legal_str
from flask_login import current_user
from core.database.impl.account_impl import User
from core.helpers.date_helpers import get_date_minus_format_ipms, get_date_now_format_ipms, \
    get_date_now_format_elastic, get_date_now
from core.database.impl.tbl_deny_web_impl import TblDenyWebImpl

app_root = os.path.dirname(os.path.abspath(__file__))


@deny_web.route('/', methods=['GET'])
@login_required
def index():

    user_type = current_user.find_type_by_id(current_user.id)
    if user_type == 'editor' or user_type == 'admin_web':
        try:
            tbl_deny_web = TblDenyWebImpl()
            web_lst = tbl_deny_web.list()
        except Exception as err:
            return render_template('deny_web/error.html', info_mess=err)
    else:
        err = 'You donot have permission here'
        return render_template('deny_web/error.html', info_mess=err)
    return render_template("deny_web/index.html", err="", web_lst=web_lst)


@deny_web.route('/downloads/<filename>')
@login_required
def download(filename):
    target = os.path.join(app_root, 'static/file/')
    if not os.path.isdir(target):
        os.makedirs(target)
    path = os.path.join(target, filename)

    return send_file(path, as_attachment=True)


@deny_web.route('/add_auto', methods=['GET', 'POST'])
@login_required
def add_auto():
    row = 0
    user_type = current_user.find_type_by_id(current_user.id)
    if user_type == 'editor' or user_type == 'admin_web':

        try:
            # with open('', 'r') as outfile:
            #    reader = csv.DictReader(outfile)
            #    helpers.bulk(es, reader, index="tbl_deny_web", doc_type="_doc")
            target = os.path.join(app_root, 'static/file/')
            if not os.path.isdir(target):
                os.makedirs(target)
            tbl_deny_web = TblDenyWebImpl()
            if request.method == 'POST':

                f = request.files['fileInput']
                file_name = f.filename or ''
                fstring_byte = f.read()
                fstring = ''

                if isinstance(fstring_byte, bytes):
                    fstring = fstring_byte.decode("ISO-8859-1")
                elif isinstance(fstring_byte, str):
                    fstring = fstring_byte

                csv_lst = [{k: v for k, v in row.items()} for row in
                           csv.DictReader(fstring.splitlines(), skipinitialspace=True)]
                if csv_lst:
                    # bat dau insert
                    # thay doi kieu. Insert vao MYSQL khong vao ES nua
                    user_login = current_user.username
                    user_type = current_user.find_type_by_id(current_user.id)
                    stat_new = 0
                    timestamp = get_date_now_format_elastic()

                    for x in csv_lst:
                        if 'URL' in x:
                            web_name = x['URL']
                            document = x['document']
                            print(web_name)
                            check_web = check_legal_str(web_name)
                            if user_type == 'editor' or user_type == 'admin_web':
                                if check_web:
                                    post_dct = dict(web=web_name, usr='', cv=document, usr_order=user_login, timestamp=timestamp,
                                                    status=stat_new)
                                    res_ins = tbl_deny_web.post(**post_dct)
                                    if res_ins:
                                        row += 1
                                    print(res_ins)
                        else:
                            print("No URL in x:" + str(x))

        except Exception as error:
            flash(error, 'info')
            return render_template('deny_web/error.html', info_mess=error)

        mes_str = "Input successfull " + str(row) + " row."
        flash(mes_str, 'info')
    else:
        err = "You don't have permission here"
        return render_template('deny_web/error.html', info_mess=err)
    return render_template('deny_web/add_auto.html', err=mes_str)


@deny_web.route('/add_manual/', methods=['GET', 'POST'])
@login_required
def add_manual():
    user_type = current_user.find_type_by_id(current_user.id)
    if user_type == 'editor' or user_type == 'admin_web':

        chek_form = DenyWebForm(request.form)
        info_mess = "Input Web to be denied"
        tbl_deny_web = TblDenyWebImpl()
        try:
            if request.method == 'POST':
                user_login = current_user.username
                user_type = current_user.find_type_by_id(current_user.id)
                stat_new = 0
                timestamp = get_date_now_format_elastic()
                web = chek_form.web.data
                document = chek_form.document.data
                check_web = check_legal_str(web)
                if user_type == 'editor' or user_type == 'admin_web':
                    if check_web:
                        post_dct = dict(web=web, usr='', cv=document, usr_order=user_login, timestamp=timestamp, status=stat_new)
                        res = tbl_deny_web.post(**post_dct)
                        if res:
                            info_mess = "Input Successful 1 web"
                        else:
                            info_mess = "Input Fail!!!"
                    else:
                        info_mess = "Web link not correct"
                else:
                    info_mess = "You don't have permission here!"
        except Exception as err:
            return render_template('deny_web/error.html', info_mess=err)
    else:
        err = "You don't have permission here"
        return render_template('deny_web/error.html', info_mess=err)

    return render_template('deny_web/add.html', info_mess=info_mess, form=chek_form)


@deny_web.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    info_mess = "Error!!!"
    user_type = current_user.find_type_by_id(current_user.id)
    if user_type == 'editor' or user_type == 'admin_web':

        try:
            tbl_deny_web = TblDenyWebImpl()
            tbl_obj = tbl_deny_web.get(id)
            if tbl_obj:
                check_form = DenyWebForm(request.form, obj=tbl_obj[0])
                stat_old = tbl_obj[0].get('status')
                post_dct = dict()
                if request.method == 'POST':
                    user_login = current_user.username
                    user_type = current_user.find_type_by_id(current_user.id)
                    # Chi user admin_web moi co the Accept chan web. User thuong thi chi edit duoc ten web thoi
                    web = check_form.web.data
                    document = check_form.document.data
                    stat_new = int(check_form.status.data)
                    timestamp = get_date_now_format_elastic()
                    chck_pri = False
                    if user_type == 'editor':
                        if stat_old != stat_new:
                            info_mess = "You don't have permission to change the status"
                        else:
                            post_dct = dict(Id=id, web=web, cv=document, usr_order=user_login, timestamp=timestamp,
                                            status=stat_old)

                            if 'usr_acc' in tbl_obj[0]:
                                user_acc = tbl_obj[0].get('usr_acc')
                                post_dct['usr_acc'] = user_acc
                            if 'usr_order' in tbl_obj[0]:
                                user_ord = tbl_obj[0].get('usr_order')
                                post_dct['usr_order'] = user_ord

                            if 'time_acc' in tbl_obj[0]:
                                time_acc = tbl_obj[0].get('time_acc')
                                post_dct['time_acc'] = time_acc
                            if 'usr' in tbl_obj[0]:
                                usr = tbl_obj[0].get('usr')
                                post_dct['usr'] = usr

                            chck_pri = True
                    elif user_type == 'admin_web':
                        if stat_new != stat_old:
                            post_dct = dict(Id=id, web=web, cv=document, usr_acc=user_login, time_acc=timestamp, status=stat_new)
                        else:
                            post_dct = dict(Id=id, web=web, cv=document, status=stat_new, time_acc=timestamp)
                        if 'usr_acc' in tbl_obj[0]:
                            user_acc = tbl_obj[0].get('usr_acc')
                            post_dct['usr_acc'] = user_acc

                        if 'usr' in tbl_obj[0]:
                            usr = tbl_obj[0].get('usr')
                            post_dct['usr'] = usr
                        if 'usr_order' in tbl_obj[0]:
                            user_ord = tbl_obj[0].get('usr_order')
                            post_dct['usr_order'] = user_ord
                        if 'timestamp' in tbl_obj[0]:
                            time_ord = tbl_obj[0].get('timestamp')
                            post_dct['timestamp'] = time_ord

                        chck_pri = True
                    else:
                        info_mess = "You don't have privellege to change the status"

                    if post_dct and chck_pri:
                        res = tbl_deny_web.put(id, **post_dct)
                        if res:
                            info_mess = "Edit Successful 1 web"
                        else:
                            info_mess = "Edit Fail!!!"

app/templates/deny_web/__init__.py
__author__ = 'VTN-DHML-DHIP10'

app/templates/deny_web/add.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/deny_web/">Deny Web</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>Input Deny Web</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    Add Deny Web
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>ADD NEW COIN
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{url_for('deny_web.add_manual')}}" class="horizontal-form"  method = "POST">
        <div class="form-body">
            <h3 class="form-section">WEB INFORMATION</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">WEB NAME</label>
                         {{form['web'](class = 'form-control input-mask', placeholder = "WEB NAME")}}
                          <span class="help-block"> Example: google.com </span>
                    </div>
                </div>
            <!--/span-->
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">DOCUMENT</label>
                        {{form['document'](class = 'form-control input-mask', placeholder = 'DOCUMENT')}}
                        <span class="help-block"> Example: CV-1234-5678 </span>
                    </div>
                </div>
            <!--/span-->
            </div>


        </div>

        <div class="form-actions right">
            <button type="button" class="btn default">Cancel</button>
            <button type="submit" class="btn blue" id="alert_show">
                <i class="fa fa-check"></i> Save</button>
        </div>
    </form><!-- END FORM-->
    </div>
    </div>
    </div>

{% endblock %}

app/templates/deny_web/add_auto.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/deny_web/">Deny Web</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>Check History Deny Web</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    Check History Deny Web
    {% if (err != "") %}
        <strong> <h3> Error: {{ err }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}

    <br/>
    <div class="table-responsive">
        <form action="" class="horizontal-form" id="ajax_form" method="post" enctype="multipart/form-data">
             <div class="form-group">
                 <label for="exampleInputFile1">File input</label>
                 <input type="file" name="fileInput">
                 <p class="help-block"> Input CSV file with format URL/CV. </p>
                <a href="{{ url_for('deny_web.download', filename= 'deny.csv') }}"> Template File</a>
                 <div class="form-actions right">
                    <button type="submit" class="btn blue" id="alert_show">
                    <i class="fa fa-check"></i> OK</button>

                </div>
             </div>

         </form>
    </div>

{% endblock %}

app/templates/deny_web/delete.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/deny_web/">Deny Web</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>Input Deny Web</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    Delete Deny Web
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Delete Web
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{url_for('deny_web.delete', id=id_web)}}" class="horizontal-form"  method = "POST">
        <div class="form-body">
            <h3 class="form-section">Do you want to delete this web ?</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">WEB NAME</label>
                         {{form['web'](class = 'form-control input-mask', placeholder = "WEB NAME", value=tbl_obj.web)}}
                          <span class="help-block"> Example: google.com </span>
                    </div>
                </div>
            <!--/span-->
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">DOCUMENT</label>
                        {{form['document'](class = 'form-control input-mask', placeholder = 'DOCUMENT', value=tbl_obj.cv)}}
                        <span class="help-block"> Example: CV-1234-5678 </span>
                    </div>
                </div>
            <!--/span-->
            </div>
            <!--/row-->

        </div>

        <div class="form-actions right">
            <button type="button" class="btn default">Cancel</button>
            <button type="submit" class="btn blue" id="alert_show">
                <i class="fa fa-check"></i> Yes</button>
        </div>
    </form><!-- END FORM-->
    </div>
    </div>
    </div>

{% endblock %}

app/templates/deny_web/edit.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/deny_web/">Deny Web</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>Input Deny Web</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    Edit Deny Web
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Edit Web
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{url_for('deny_web.edit', id=id_web)}}" class="horizontal-form"  method = "POST">
        <div class="form-body">
            <h3 class="form-section">WEB INFORMATION</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">WEB NAME</label>
                         {{form['web'](class = 'form-control input-mask', placeholder = "WEB NAME", value=tbl_obj.web)}}
                          <span class="help-block"> Example: google.com </span>
                    </div>
                </div>
            <!--/span-->
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">DOCUMENT</label>
                        {{form['document'](class = 'form-control input-mask', placeholder = 'DOCUMENT', value=tbl_obj.cv )}}
                        <span class="help-block"> Example: CV-1234-5678 </span>
                    </div>
                </div>
            <!--/span-->
            </div>
            <!--/row-->
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">ACCEPT/DENY ?</label>
                        {{form['status'](class = 'form-control input-mask', placeholder = "ACCEPT/DENY/WAITING"
                                         )}}
                         <span class="help-block"> Example: ACCEPT </span>
                    </div>
                </div>
            <!--/span-->

            </div>

        </div>

        <div class="form-actions right">
            <button type="button" class="btn default">Cancel</button>
            <button type="submit" class="btn blue" id="alert_show">
                <i class="fa fa-check"></i> Save</button>
        </div>
    </form><!-- END FORM-->
    </div>
    </div>
    </div>

{% endblock %}

app/templates/deny_web/error.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/deny_web/">Deny Web</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>Input Deny Web</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    Input Deny Web
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>EDIT WEB DENY
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->

    </div>
    </div>
    </div>

{% endblock %}

app/templates/deny_web/index.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/deny_web/">Deny Web</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>Check History Deny Web</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    Check History Deny Web
    {% if (err != "") %}
        <strong> <h3> Error: {{ err }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}

    <br/>
    <div class="table-responsive">
        <form action="" class="horizontal-form" id="ajax_form" method="post">
                <table class="table table-bordered" id="myTable">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> WEB  </th>
                                <th> USER ACTION </th>
                                <th> DOCUMENT</th>
                                <th> USER ORDER</th>
                                <th> TIME ORDER</th>
                                <th> USER CHECK</th>
                                <th> TIME CHECK</th>
                                <th> STATUS</th>
                                <th> Edit/Delete</th>

                            </tr>

                        </thead>
                        <tbody>
                            {%for x in web_lst%}
                            <tr>
                                <td> {{loop.index}} </td>
                                <td> {{x.web}} </td>
                                <td> {{x.usr}} </td>
                                <td> {{x.cv}} </td>
                                <td> {{x.usr_order}} </td>
                                <td> {{x.timestamp}} </td>
                                <td> {{x.usr_acc}} </td>
                                <td> {{x.time_acc}} </td>
                                <td>
                                     {% if (x.status == 0) %}
                                        DENY
                                     {% endif %}
                                     {% if (x.status == 1) %}
                                        ACCEPT
                                    {% endif %}
                                    {% if (x.status == 2) %}
                                        WAITING
                                    {% endif %}
                                </td>

                                <td> <a href = {{ url_for('deny_web.edit', id = x.Id) }}> Edit/</a>
                                    <a href = {{ url_for('deny_web.delete', id = x.Id) }}> Delete</a>
                                </td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
         </form>
    </div>

{% endblock %}