app/controllers/nocpro_afe/forms.py
from wtforms import StringField, DateField, BooleanField, Form, IntegerField, SelectField, validators

class SearchForm(Form):
    key_name = StringField(u'Search',)

app/controllers/nocpro_afe/__init__.py
from flask import Blueprint
nocpro_afe = Blueprint('nocpro_afe', __name__)
from . import views

app/controllers/nocpro_afe/views.py
# -*- coding:utf-8 -*-
from flask import render_template, flash, request, redirect, url_for
from app.controllers.nocpro_afe import nocpro_afe
from flask_login import login_required
from flask import send_file
from flask_paginate import Pagination, get_page_args
import os, json
import csv
from app.controllers.deny_web.forms import DenyWebForm
import uuid
from core.helpers.stringhelpers import check_legal_str
from flask_login import current_user
from core.database.impl.account_impl import User
from core.helpers.date_helpers import get_date_minus_format_ipms, get_date_now_format_ipms, \
    get_date_now_format_elastic, get_date_now
from core.database.impl.nocpro.tbl_afe_cat_data_free_load import TblAfeCatDataFreeLoad
from .forms import SearchForm

app_root = os.path.dirname(os.path.abspath(__file__))


def get_users(tbl_lst, offset=0, per_page=50):
    return tbl_lst[offset: offset + per_page]


@nocpro_afe.route('/', methods=['GET'])
@login_required
def index():
    tbl_bkk = TblAfeCatDataFreeLoad()
    chek_form = SearchForm(request.form)
    tbl_lst = []
    try:
        user_type = current_user.find_type_by_id(current_user.id)
        if user_type == 'editor' or user_type == 'admin_web':
            tbl_lst = tbl_bkk.get_lst()
        else:
            flash("You don't have permission here!")
            redirect(url_for('nocpro_afe.index'))

        page, per_page, offset = get_page_args(page_parameter='page',
                                               per_page_parameter='per_page')
        total = len(tbl_lst)
        pagination_tbl = get_users(tbl_lst, offset=offset, per_page=10)
        pagination = Pagination(page=page, per_page=per_page, total=total, css_framework='bootstrap4')
        return render_template("nocpro_afe/index.html", err="", tbl_lst=pagination_tbl,
                               page=page,
                               per_page=per_page,
                               pagination=pagination,
                               form=chek_form,
                               key_name='')
    except Exception as err:

        tbl_bkk = TblAfeCatDataFreeLoad()
        tbl_lst = tbl_bkk.get_lst()
        flash(err)
        return render_template("nocpro_afe/index.html", tbl_lst=tbl_lst, form=chek_form,
                               key_name='')


@nocpro_afe.route('/search/', methods=['POST'])
@login_required
def index_srch():
    chek_form = SearchForm(request.form)

    try:
        user_type = current_user.find_type_by_id(current_user.id)
        if user_type == 'editor' or user_type == 'admin_web':
            if request.method == 'POST':
                key_name_new = chek_form.key_name.data
                if key_name_new:
                    return redirect(url_for('nocpro_afe.index_srch_pretty', key_name=key_name_new))
                else:
                    return redirect(url_for('nocpro_afe.index'))

        else:
            flash("You don't have permission here!")
            redirect(url_for('nocpro_afe.index'))

    except Exception as err:
        flash(err)
        return redirect(url_for('nocpro_afe.index'))


@nocpro_afe.route('/search/<key_name>')
@login_required
def index_srch_pretty(key_name):

    tbl_bkk = TblAfeCatDataFreeLoad()
    chek_form = SearchForm(request.form)
    tbl_lst = []
    try:
        user_type = current_user.find_type_by_id(current_user.id)
        if user_type == 'editor' or user_type == 'admin_web':
            chek_form.key_name.default = key_name
            chek_form.process()
            tbl_lst = tbl_bkk.find_like(key_name)
        else:
            flash("You don't have permission here!")
            redirect(url_for('nocpro_afe.index', key_name=key_name))

        page, per_page, offset = get_page_args(page_parameter='page',
                                               per_page_parameter='per_page')
        total = len(tbl_lst)
        pagination_tbl = get_users(tbl_lst, offset=offset, per_page=10)
        pagination = Pagination(page=page, per_page=per_page, total=total, css_framework='bootstrap4')
        return render_template("nocpro_afe/index.html", err="", tbl_lst=pagination_tbl,
                               page=page,
                               per_page=per_page,
                               pagination=pagination,
                               form=chek_form,
                               key_name=key_name)
    except Exception as err:

        tbl_bkk = TblAfeCatDataFreeLoad()
        tbl_lst = tbl_bkk.get_lst()
        flash(err)
        return render_template("nocpro_afe/index.html", tbl_lst=tbl_lst, form=chek_form,
                               key_name=key_name)

app/templates/nocpro_afe/__init__.py
__author__ = 'VTN-DHML-DHIP10'

app/templates/nocpro_afe/add.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/afe/">NOCPRO AFE RULE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>AFE Rule</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    ADD NOCPRO AFE RULE
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>ADD NEW AFE RULE
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{url_for('nocpro_afe.add')}}" class="horizontal-form"  method = "POST">
        <div class="form-body">
            <h3 class="form-section">AFE RULE INFORMATION</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">DEVICE NAME</label>
                         {{form['device_name'](class = 'form-control input-mask', placeholder = "DEVICE NAME")}}
                          <span class="help-block"> Example: PECD01 </span>
                    </div>
                </div>
            <!--/span-->
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">SYSTEM</label>
                        {{form['system_code'](class = 'form-control input-mask', placeholder = 'SYSTEM')}}
                        <span class="help-block"> Example: SYSLOG_IP_CORE </span>
                    </div>
                </div>
            <!--/span-->
            </div>


        </div>

        <div class="form-actions right">
            <button type="submit" class="btn blue" id="alert_show">
                <i class="fa fa-check"></i> Save</button>
        </div>
    </form><!-- END FORM-->
    </div>
    </div>
    </div>

{% endblock %}

app/templates/nocpro_afe/delete.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/afe/">NOCPRO AFE RULE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>AFE Rule</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    DELETE NOCPRO AFE RULE
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>DELETE NOCPRO AFE RULE
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{url_for('nocpro_afe.delete', id=id_rule)}}" class="horizontal-form"  method = "POST">
        <div class="form-body">
            <h3 class="form-section">Do you want to delete this rule ?</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">AFE RULE</label>
                         {{form['device_name'](class = 'form-control input-mask', placeholder = "AFE RULE", value=tbl_obj.device_name)}}
                          <span class="help-block"> Example: PECD01 </span>
                    </div>
                </div>
            <!--/span-->
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">SYSTEM</label>
                        {{form['system_code'](class = 'form-control input-mask', placeholder = 'DOCUMENT', value=tbl_obj.system_code)}}
                        <span class="help-block"> Example: SYSLOG_IP_CORE </span>
                    </div>
                </div>
            <!--/span-->
            </div>
            <!--/row-->

        </div>

        <div class="form-actions right">
            <button type="submit" class="btn blue" id="alert_show">
                <i class="fa fa-check"></i> Yes</button>
        </div>
    </form><!-- END FORM-->
    </div>
    </div>
    </div>

{% endblock %}

app/templates/nocpro_afe/edit.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/afe/">NOCPRO AFE RULE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>AFE Rule</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    EDIT NOCPRO AFE RULE
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>Edit Web
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="{{url_for('nocpro_afe.edit', id=id_rule)}}" class="horizontal-form"  method = "POST">
        <div class="form-body">
            <h3 class="form-section">AFE RULE INFORMATION</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">DEVICE NAME</label>
                         {{form['device_name'](class = 'form-control input-mask', placeholder = "DEVICE NAME", value=tbl_obj.device_name)}}
                          <span class="help-block"> Example: PECD01 </span>
                    </div>
                </div>
            <!--/span-->
                <div class="col-md-6">
                    <div class="form-group has-error">
                        <label class="control-label">DOCUMENT</label>
                        {{form['system_code'](class = 'form-control input-mask', placeholder = 'SYSTEM', value=tbl_obj.system_code)}}
                        <span class="help-block"> Example: SYSLOG_IP_CORE </span>
                    </div>
                </div>
            <!--/span-->
            </div>
            <!--/row-->


        </div>

        <div class="form-actions right">
            <button type="button" class="btn default">Cancel</button>
            <button type="submit" class="btn blue" id="alert_show">
                <i class="fa fa-check"></i> Save</button>
        </div>
    </form><!-- END FORM-->
    </div>
    </div>
    </div>

{% endblock %}

app/templates/nocpro_afe/error.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/afe/">NOCPRO AFE RULE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>AFE Rule</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    NOCPRO AFE RULE
    {% if (info_mess != "") %}
        <strong> <h3> Info: {{ info_mess }}</h3></strong>
    {% endif %}
{%endblock%}
{% block content%}
    <div class="tab-pane" id="tab_1">
    <div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>ERROR AFE RULE
        </div>

    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->

    </div>
    </div>
    </div>

{% endblock %}

app/templates/nocpro_afe/index.html
{% extends "_layout_schedule.html"%}
{% block title %}Viettel Localized Incidents{% endblock %}
{%block pagebar%}
 <ul class="page-breadcrumb">
    <li>
        <a href="/home">HOMEPAGE</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="/afe/">NOCPRO NODE FREE LOAD</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span>AFE NODE FREE LOAD</span>
    </li>
</ul>
{%endblock%}
{%block pagetitle%}
    NOCPRO FREE LOAD

{%endblock%}
{% block content%}

    <br/>
    <div class="table-responsive">
        <form action="{{ url_for('nocpro_afe.index_srch') }}" class="horizontal-form" id="ajax_form" method="post">
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-3">
                                 {{form['key_name'](class = 'form-control input-mask', placeholder = "Search")}}
                        </div>
                        <div class="col-md-3">
                            <button type="submit" class="btn blue" id="alert_show">
                                <i class="fa fa-check">Search</i>
                            </button>
                        </div>
                    </div>
                    <table class="table table-bordered ">
                        <thead>
                            <tr>

                                <th> SYSTEM  </th>
                                <th> DEVICE NAME </th>
                                <th> FAULT NAME</th>
                                <th> OBJECT NAME</th>
                                <th> TYPE</th>
                                <th> DEST NNAME</th>
                                <th> USER UPDATE</th>
                                <th> INSERT TIME</th>
                                <th> UPDATE TIME</th>

                            </tr>

                        </thead>
                        <tbody>
                            {%for x in tbl_lst%}
                            <tr>
                                <td> {{x['SYSTEM_CODE']}} </td>
                                <td> {{x['DEVICE_NAME']}} </td>
                                <td> {{x['FAULT_NAME']}} </td>
                                <td> {{x['OBJECT_NAME']}} </td>
                                <td> {{x['TYPE']}} </td>
                                <td> {{x['DEST_NAME']}} </td>
                                <td> {{x['USER_UPDATE']}} </td>
                                <td> {{x['INSERT_TIME']}} </td>
                                <td> {{x['UPDATE_TIME']}} </td>

                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    <div align="right" >{{ pagination.links }} </div>
                </div>
         </form>
    </div>

{% endblock %}